export { ReactComponent as Angle } from "assets/angle.svg";
export { ReactComponent as Attention } from "assets/attention.svg";
export { ReactComponent as Bell } from "assets/bell.svg";
export { ReactComponent as Cross } from "assets/cross.svg";
export { ReactComponent as Done } from "assets/done.svg";
export { ReactComponent as Download } from "assets/download.svg";
export { ReactComponent as Personal } from "assets/personal.svg";
export { ReactComponent as SignOut } from "assets/sign-out.svg";
export { ReactComponent as Tiles } from "assets/tiles.svg";
